<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- ORM & DB -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2" />
    <PackageVersion Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageVersion Include="Dapper" Version="2.1.72" />
    <PackageVersion Include="MySqlConnector" Version="2.4.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.2" />

    <!-- Routing -->
    <PackageVersion Include="Carter" Version="8.2.1" />

    <!-- Logging -->
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageVersion Include="Serilog.Enrichers.Process" Version="3.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="6.0.0" />

    <!-- Resilience -->
    <PackageVersion Include="Polly" Version="8.5.2" />

    <!-- API & Health -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.2" />
  </ItemGroup>
</Project>
