// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AccessApprovalEntity", b =>
                {
                    b.Property<int>("AccessApproveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("accessapprove_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccessApproveId"));

                    b.Property<int>("AccessItemId")
                        .HasColumnType("int")
                        .HasColumnName("accessitem_id");

                    b.Property<int>("AccessReqId")
                        .HasColumnType("int")
                        .HasColumnName("accessreq_id");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int")
                        .HasColumnName("approval_status");

                    b.Property<int>("ApproverId")
                        .HasColumnType("int")
                        .HasColumnName("approver_id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("AccessApproveId");

                    b.ToTable("jan_accessapproval", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AccessItemEntity", b =>
                {
                    b.Property<int>("AccessItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("accessitem_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccessItemId"));

                    b.Property<int>("AccessReqId")
                        .HasColumnType("int")
                        .HasColumnName("accessreq_id");

                    b.Property<int>("AccessType")
                        .HasColumnType("int")
                        .HasColumnName("access_type");

                    b.Property<int>("ConfirmAccessType")
                        .HasColumnType("int")
                        .HasColumnName("confirm_access_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("folder_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticket_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("AccessItemId");

                    b.HasIndex("AccessReqId");

                    b.ToTable("jan_accessitems", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AccessReqAuditEntity", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("audit_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<int?>("AccessApproveId")
                        .HasColumnType("int")
                        .HasColumnName("accessapprove_id");

                    b.Property<int?>("AccessItemId")
                        .HasColumnType("int")
                        .HasColumnName("accessitem_id");

                    b.Property<int>("AccessReqId")
                        .HasColumnType("int")
                        .HasColumnName("accessreq_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<int>("RecipientEmpId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_emp_id");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientRole")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("recipient_role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("AuditId");

                    b.ToTable("jan_accessreqaudit", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AccessRequestEntity", b =>
                {
                    b.Property<int>("AccessReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("accessreq_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccessReqId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAgreed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_agreed");

                    b.Property<string>("ItsrNo")
                        .HasColumnType("longtext")
                        .HasColumnName("itsr_no");

                    b.Property<int>("ReqTo")
                        .HasColumnType("int")
                        .HasColumnName("req_to");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("AccessReqId");

                    b.ToTable("jan_accessrequest", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DepartmentEntity", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dept_name");

                    b.Property<int>("HodId")
                        .HasColumnType("int")
                        .HasColumnName("hod_id");

                    b.HasKey("DepartmentId");

                    b.ToTable("jan_department", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserRole")
                        .HasColumnType("int")
                        .HasColumnName("user_role");

                    b.HasKey("UserId");

                    b.ToTable("jan_portal_users", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.FolderMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("folder_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PrimaryHodEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("primary_hod_email");

                    b.Property<string>("PrimaryHodId")
                        .HasColumnType("longtext")
                        .HasColumnName("primary_hod_id");

                    b.Property<string>("PrimaryHodName")
                        .HasColumnType("longtext")
                        .HasColumnName("primary_hod_name");

                    b.Property<string>("SecondaryHodEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("secondary_hod_email");

                    b.Property<string>("SecondaryHodId")
                        .HasColumnType("longtext")
                        .HasColumnName("secondary_hod_id");

                    b.Property<string>("SecondaryHodName")
                        .HasColumnType("longtext")
                        .HasColumnName("secondary_hod_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FolderName")
                        .IsUnique();

                    b.ToTable("jan_folder_mappings", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AccessItemEntity", b =>
                {
                    b.HasOne("Domain.Entities.AccessRequestEntity", null)
                        .WithMany("AccessItems")
                        .HasForeignKey("AccessReqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AccessRequestEntity", b =>
                {
                    b.Navigation("AccessItems");
                });
#pragma warning restore 612, 618
        }
    }
}
